### Site Settings ###
title               : Azmain Adel
subtitle            : CS Graduate | Software Engineer
description         : >-
                      "I turn coffee :coffee: into code,
                      use tabs over spaces
                      and sometimes despise myself as a software engineer."
                      
baseurl             : ""      
name                : Azmain Adel   
repository          : azmainadel           


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/projects.html


### Author Info ###
author:
  name              : Azmain Adel
  image             : assets/img/avatar.png
  email             : azmainadel47@gmail.com
  linkedin          : azmainadel
  github            : azmainadel
  facebook          : azmainadelsheesh
  twitter           : azmainadel_
  behance           : azmainadel
  medium            : azmainadel
# gitlab            : your_username
# instagram         : your_username
# dribbble          : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : azmainadel_
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title

### Google Services ###
google_analytics: UA-160210255-1

### Disqus ###
disqus:
    shortname: azmainadel

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
