### Site Settings ###
title               : Azmain Adel
description         : >-
                      "I turn coffee :coffee: into code,
                      use tabs over spaces
                      and sometimes despise myself as a software engineer."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
# repository          : azmainadel    # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Azmain Adel
  image             : assets/img/avatar.png
  email             : azmainadel47@gmail.com
  github            : azmainadel
  linkedin          : azmainadel
  behance           : xyntherys
  medium            : azmainadel
  facebook          : azmainadelsheesh
# gitlab            : your_username
# instagram         : your_username
# dribbble          : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
